name: TK
favicon: null
layout_spectrum: 1
typography_spectrum: 0.06623
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#053e49'
    - '#a6b5d6'
    - '#7587ab'
    - '#0b0800'
    - '#9b5c5a'
  brandStrength: 0
  lightness: 0.6901517568621784
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
